export const literatureData = [
  ["阿司匹林", "Aspirin, adverse effects, toxicity, ADR", "Acetylsalicylic acid, ASA", "(\"Aspirin\"[MeSH] OR \"Aspirin\"[Title/Abstract] OR \"阿司匹林\"[Title/Abstract] OR \"Acetylsalicylic acid\"[Title/Abstract] OR \"ASA\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["布洛芬", "Ibuprofen, adverse effects, GI bleeding, toxicity", "Isobutylphenylpropanoic acid, Advil, Motrin", "(\"Ibuprofen\"[MeSH] OR \"Ibuprofen\"[Title/Abstract] OR \"布洛芬\"[Title/Abstract] OR \"Isobutylphenylpropanoic acid\"[Title/Abstract] OR \"Advil\"[Title/Abstract] OR \"Motrin\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"GI bleeding\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["二甲双胍", "Metformin, adverse effects, lactic acidosis", "Dimethylbiguanide, Glucophage", "(\"Metformin\"[MeSH] OR \"Metformin\"[Title/Abstract] OR \"二甲双胍\"[Title/Abstract] OR \"Dimethylbiguanide\"[Title/Abstract] OR \"Glucophage\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"lactic acidosis\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["阿托伐他汀", "Atorvastatin, adverse effects, myopathy, toxicity", "Lipitor", "(\"Atorvastatin\"[MeSH] OR \"Atorvastatin\"[Title/Abstract] OR \"阿托伐他汀\"[Title/Abstract] OR \"Lipitor\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"myopathy\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["奥美拉唑", "Omeprazole, adverse effects, bone fracture", "Losec, Prilosec", "(\"Omeprazole\"[MeSH] OR \"Omeprazole\"[Title/Abstract] OR \"奥美拉唑\"[Title/Abstract] OR \"Losec\"[Title/Abstract] OR \"Prilosec\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"bone fracture\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["氨氯地平", "Amlodipine, adverse effects, peripheral edema", "Norvasc", "(\"Amlodipine\"[MeSH] OR \"Amlodipine\"[Title/Abstract] OR \"氨氯地平\"[Title/Abstract] OR \"Norvasc\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"peripheral edema\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["氯吡格雷", "Clopidogrel, adverse effects, hemorrhage, bleeding", "Plavix", "(\"Clopidogrel\"[MeSH] OR \"Clopidogrel\"[Title/Abstract] OR \"氯吡格雷\"[Title/Abstract] OR \"Plavix\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"hemorrhage\"[Title/Abstract] OR \"bleeding\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["塞来昔布", "Celecoxib, adverse effects, cardiovascular events", "Celebrex", "(\"Celecoxib\"[MeSH] OR \"Celecoxib\"[Title/Abstract] OR \"塞来昔布\"[Title/Abstract] OR \"Celebrex\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"cardiovascular events\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["对乙酰氨基酚", "Acetaminophen, adverse effects, hepatotoxicity", "Paracetamol, Tylenol", "(\"Acetaminophen\"[MeSH] OR \"Acetaminophen\"[Title/Abstract] OR \"对乙酰氨基酚\"[Title/Abstract] OR \"Paracetamol\"[Title/Abstract] OR \"Tylenol\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"hepatotoxicity\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["瑞舒伐他汀", "Rosuvastatin, adverse effects, rhabdomyolysis", "Crestor", "(\"Rosuvastatin\"[MeSH] OR \"Rosuvastatin\"[Title/Abstract] OR \"瑞舒伐他汀\"[Title/Abstract] OR \"Crestor\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"rhabdomyolysis\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["缬沙坦", "Valsartan, adverse effects, hyperkalemia", "Diovan", "(\"Valsartan\"[MeSH] OR \"Valsartan\"[Title/Abstract] OR \"缬沙坦\"[Title/Abstract] OR \"Diovan\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"hyperkalemia\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["达格列净", "Dapagliflozin, adverse effects, urinary tract infection", "Farxiga, Forxiga", "(\"Dapagliflozin\"[MeSH] OR \"Dapagliflozin\"[Title/Abstract] OR \"达格列净\"[Title/Abstract] OR \"Farxiga\"[Title/Abstract] OR \"Forxiga\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"urinary tract infection\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["艾司西酞普兰", "Escitalopram, adverse effects, suicidal ideation", "Lexapro, Cipralex", "(\"Escitalopram\"[MeSH] OR \"Escitalopram\"[Title/Abstract] OR \"艾司西酞普兰\"[Title/Abstract] OR \"Lexapro\"[Title/Abstract] OR \"Cipralex\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"suicidal ideation\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["沙丁胺醇", "Albuterol, adverse effects, tachycardia", "Salbutamol, Ventolin", "(\"Albuterol\"[MeSH] OR \"Albuterol\"[Title/Abstract] OR \"沙丁胺醇\"[Title/Abstract] OR \"Salbutamol\"[Title/Abstract] OR \"Ventolin\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"tachycardia\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["孟鲁司特", "Montelukast, adverse effects, neuropsychiatric events", "Singulair", "(\"Montelukast\"[MeSH] OR \"Montelukast\"[Title/Abstract] OR \"孟鲁司特\"[Title/Abstract] OR \"Singulair\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"neuropsychiatric events\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["泮托拉唑", "Pantoprazole, adverse effects, interstitial nephritis", "Protonix", "(\"Pantoprazole\"[MeSH] OR \"Pantoprazole\"[Title/Abstract] OR \"泮托拉唑\"[Title/Abstract] OR \"Protonix\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"interstitial nephritis\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["氯沙坦", "Losartan, adverse effects, renal impairment", "Cozaar", "(\"Losartan\"[MeSH] OR \"Losartan\"[Title/Abstract] OR \"氯沙坦\"[Title/Abstract] OR \"Cozaar\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"renal impairment\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["美托洛尔", "Metoprolol, adverse effects, bradycardia", "Lopressor, Toprol", "(\"Metoprolol\"[MeSH] OR \"Metoprolol\"[Title/Abstract] OR \"美托洛尔\"[Title/Abstract] OR \"Lopressor\"[Title/Abstract] OR \"Toprol\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"bradycardia\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["氟康唑", "Fluconazole, adverse effects, QT prolongation", "Diflucan", "(\"Fluconazole\"[MeSH] OR \"Fluconazole\"[Title/Abstract] OR \"氟康唑\"[Title/Abstract] OR \"Diflucan\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"QT prolongation\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["阿奇霉素", "Azithromycin, adverse effects, arrhythmia", "Zithromax", "(\"Azithromycin\"[MeSH] OR \"Azithromycin\"[Title/Abstract] OR \"阿奇霉素\"[Title/Abstract] OR \"Zithromax\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"arrhythmia\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["帕罗西汀", "Paroxetine, adverse effects, withdrawal syndrome", "Paxil, Seroxat", "(\"Paroxetine\"[MeSH] OR \"Paroxetine\"[Title/Abstract] OR \"帕罗西汀\"[Title/Abstract] OR \"Paxil\"[Title/Abstract] OR \"Seroxat\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"withdrawal syndrome\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["舍曲林", "Sertraline, adverse effects, insomnia", "Zoloft", "(\"Sertraline\"[MeSH] OR \"Sertraline\"[Title/Abstract] OR \"舍曲林\"[Title/Abstract] OR \"Zoloft\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"insomnia\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["雷米普利", "Ramipril, adverse effects, angioedema", "Altace", "(\"Ramipril\"[MeSH] OR \"Ramipril\"[Title/Abstract] OR \"雷米普利\"[Title/Abstract] OR \"Altace\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"angioedema\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["格列美脲", "Glimepiride, adverse effects, hypoglycemia", "Aryl", "(\"Glimepiride\"[MeSH] OR \"Glimepiride\"[Title/Abstract] OR \"格列美脲\"[Title/Abstract] OR \"Aryl\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"hypoglycemia\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"],
  ["华法林", "Warfarin, adverse effects, major bleeding", "Coumadin, Jantoven", "(\"Warfarin\"[MeSH] OR \"Warfarin\"[Title/Abstract] OR \"华法林\"[Title/Abstract] OR \"Coumadin\"[Title/Abstract] OR \"Jantoven\"[Title/Abstract]) AND (\"adverse effects\"[Subheading] OR \"toxicity\"[Subheading] OR \"Drug-Related Side Effects and Adverse Reactions\"[MeSH] OR \"side effect\"[Title/Abstract] OR \"adverse reaction\"[Title/Abstract] OR \"toxic\"[Title/Abstract] OR \"adverse\"[Title/Abstract] OR \"major bleeding\"[Title/Abstract]) AND (\"Case Reports\"[pt] OR \"Clinical Trial\"[pt]) AND (2023[dp] OR 2024[dp] OR 2025[dp] OR 2026[dp]) NOT (\"Animals\"[Mesh] NOT \"Humans\"[Mesh])"]
];

export const getMockResults = (name: string) => {
  const result: any[] = [];
  
  if (name === "阿司匹林") {
    result.push({ pmid: "42198965", title: "[Intravenous dexamethasone enhances efficacy of brachial plexus block via the costoclavicular space: a randomized, double-blind, single-center trial].", abstract: "OBJECTIVES: To investigate the effect of intravenous 8 mg dexamethasone injection on the efficacy of ultrasound-guided brachial plexus block (BPB) with 20 mL 0.375% ropivacaine via the costoclavicular space (CCS). \nMETHODS: Eighty-four patients...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（adverse, advers）" });
    result.push({ pmid: "42186614", title: "Diffuse Alveolar Hemorrhage Mimicking Pneumonia in a Patient With Interstitial Lung Disease on Ticagrelor.", abstract: "Diffuse alveolar hemorrhage (DAH) is a rare and potentially life-threatening cause of acute hypoxemic respiratory failure and may be difficult to diagnose in patients with underlying interstitial lung disease (ILD). Ticagrelor frequently causes dyspnea, but DAH related to its use is exceedingly uncommon...", hasAdverseEvent: "是", confidence: "85", reason: "标题直接提及ADR关键词（hemorrhage），摘要命中2个相关词" });
    result.push({ pmid: "42152719", title: "Wrist-Ankle Acupuncture on Postoperative Nausea and Vomiting Prophylaxis in High-Risk Female Patients: A Pragmatic, Randomized, Single-Blind, Sham-Controlled Trial.", abstract: "BACKGROUND: Postoperative nausea and vomiting (PONV) affects up to 80% of high-risk patients, compromising Enhanced Recovery After Surgery (ERAS) outcomes and prolonging hospitalization. This randomized controlled trial evaluated wrist-ankle acupuncture (WAA) efficacy for PONV prevention in high-risk female surgical patients...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（adverse, advers）" });
  }
  
  if (name === "布洛芬") {
    result.push({ pmid: "42170735", title: "Comparative Analgesic Efficacy of Diclofenac and Ketoprofen Transdermal Patches Versus Ibuprofen Tablets for Pain Control After Initial Archwire Placement in Orthodontic Patients: A Randomized Clinical Trial.", abstract: "OBJECTIVES: This study compared the analgesic efficacy of diclofenac and ketoprofen transdermal patches versus ibuprofen tablets for pain control following initial archwire placement in orthodontic patients...", hasAdverseEvent: "否", confidence: "15", reason: "未检测到明显的不良反应关键词" });
    result.push({ pmid: "42051372", title: "Diagnostic Challenges in a Pediatric Case of Recurrent Blistering Skin Reactions: Ibuprofen-Induced Fixed Drug Exanthema versus Infection-Triggered Erythema Multiforme.", abstract: "A 12-year-old patient was hospitalized with suspected recurrent Stevens-Johnson syndrome (SJS) caused by ibuprofen. The patient presented with aphthous lesions on the lips and oral mucosa, accompanied by fever and cough...", hasAdverseEvent: "是", confidence: "85", reason: "标题直接提及ADR关键词（infection），摘要命中1个相关词" });
    result.push({ pmid: "42046557", title: "Ibuprofen-Induced Pemphigus Vulgaris: A Case Report.", abstract: "Pemphigus Vulgaris (PV) is a chronic autoimmune blistering disease. Although pharmacological agents, particularly those containing thiol groups, have been identified as precipitating factors, reports of non-thiol drugs, such as nonsteroidal anti-inflammatory drugs (NSAIDs), causing PV remain limited...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（adverse, advers）" });
  }

  if (name === "二甲双胍") {
    result.push({ pmid: "42196606", title: "Diagnosing Metformin Intoxication with High-Resolution Platelet Respirometry: A Case Report.", abstract: "Metformin-associated lactic acidosis (MALA) involves mitochondrial Complex I inhibition, traditionally diagnosed via indirect markers. We present platelet high-resolution respirometry (HRR) as a novel \"liquid biopsy\" to directly quantify metformin-induced systemic bioenergetic lesions...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 5 个ADR关键词（toxicity, intoxication, hypoglycemia, toxic, overdose）" });
    result.push({ pmid: "42184239", title: "Sternoclavicular Joint Infection Caused by Staphylococcus capitis.", abstract: "A 74-year-old female patient presented with \"palpitations and chest tightness for half a day.\" The symptoms developed suddenly while riding an elevator, accompanied by shortness of breath, but without dizziness or chest pain...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（infection, adverse, advers）" });
    result.push({ pmid: "42164410", title: "Co-prescription of metformin and glucagon-like peptide-1 receptor agonists and metformin-associated lactic acidosis: A case series.", abstract: "Metformin-associated lactic acidosis (MALA) is a rare phenomenon mostly described in the setting of impaired renal elimination or following an acute overdose. While metformin is first-line treatment for type 2 diabetes mellitus, glucagon-like peptide-1 (GLP-1) receptor agonists...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（overdose, adverse, advers）" });
  }

  if (name === "阿托伐他汀") {
    result.push({ pmid: "42133048", title: "The Effect of the combination therapy of statin and dapagliflozin, a selective inhibitor of sodium_glucose Co-transporter type 2, in the treatment of Ischemic heart disease with heart failure: A randomized controlled trial.", abstract: "PURPOSE: Gliflozins (SGLT2 inhibitors) and statins are key treatments commonly used in patients with ischemic heart failure. Although both are well known for diminishing cardiovascular risk and heart failure-related mortality, the possible synergistic benefits of using them together have not been thoroughly investigated...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（mortality, adverse, advers）" });
    result.push({ pmid: "42109749", title: "Longitudinal management and novel pharmacological interactions in a patient with HeFH, 21-OHD, and kawasaki disease: a 6-year clinical follow-up.", abstract: "BACKGROUND: Familial hypercholesterolemia (FH) and 21-hydroxylase deficiency (21-OHD) are both genetic disorders that significantly elevate cardiovascular risk in pediatric patients. Kawasaki disease (KD) further exacerbates this risk by causing coronary artery complications...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（adverse, advers）" });
    result.push({ pmid: "42037837", title: "Statin-Associated Immune-Mediated Necrotizing Myopathy: An Underrecognised Cause of Progressive Muscle Weakness in Primary Care.", abstract: "Statins are among the most frequently prescribed agents in primary care for lipid control and cardiovascular risk reduction. Although generally safe, they are associated with muscle-related adverse effects, ranging from myalgia and self-limiting myopathy to the rare but clinically significant immune-mediated necrotizing myopathy (IMNM)...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（myopathy, adverse, rhabdomyolysis, advers）" });
  }

  if (name === "奥美拉唑") {
    result.push({ pmid: "42199823", title: "Acute Interstitial Nephritis Is a Potential Adverse Effect in Inflammatory Bowel Disease Patients Treated With Vedolizumab: A Case Report and Review of the Literature.", abstract: "We report a case of vedolizumab (VDZ)-associated acute interstitial nephritis (AIN) in a 44-year-old man with refractory ulcerative colitis. The case highlights the need for nephrotoxicity monitoring in patients receiving VDZ for inflammatory bowel disease...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 5 个ADR关键词（toxicity, nephrotoxicity, toxic, adverse, advers）" });
    result.push({ pmid: "41854177", title: "Pharmacokinetics, Safety, and Tolerability of GS-1427, an Oral Prodrug of a Potent and Selective α4β7 Integrin Inhibitor, in Healthy Participants.", abstract: "GS-1427 is the oral prodrug of GS-1069518, an inhibitor of the α4β7 integrin, and is currently in development for the treatment of ulcerative colitis (UC). This first-in-human, phase 1, placebo-controlled study evaluated the pharmacokinetics, safety, and tolerability of GS-1427...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 5 个ADR关键词（death, tolerability, safety, adverse, advers）" });
    result.push({ pmid: "41706381", title: "Hepatic Safety of Adjunctive High-Dose Melatonin in Participants Receiving Ocrelizumab for Primary Progressive Multiple Sclerosis: Liver Toxicity Findings from a Phase I/II Randomised Clinical Trial (MELATOMS-1).", abstract: "BACKGROUND AND OBJECTIVES: Based on melatonin's neuroprotective effects in pre-clinical multiple sclerosis models, the MELATOMS-1 study was designed to evaluate melatonin treatment in patients with primary progressive multiple sclerosis (PP-MS)...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 8 个ADR关键词（toxicity, drug interaction, hepatotoxicity, adverse, safety...）" });
  }

  if (name === "氨氯地平") {
    result.push({ pmid: "42199811", title: "Efficacy and Safety of Telmisartan 20 mg/S-Amlodipine 2.5 mg versus Telmisartan 40 mg in Patients with Hypertension, Inadequately Controlled on Telmisartan 20 mg Monotherapy: A Randomized, Double-Blind, Multicenter, Phase 3 Trial.", abstract: "PURPOSE: This 8-week, randomized, double-blind study evaluated the efficacy and safety of low-dose combination of telmisartan 20 mg/S-amlodipine 2.5 mg (T20/SA2.5) versus telmisartan 40 mg (T40) monotherapy in patients with essential hypertension inadequately controlled on T20...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（safety, tolerability, adverse, advers）" });
    result.push({ pmid: "42130156", title: "Low-Dose Telmisartan/Amlodipine in Essential Hypertension: A Phase III Trial.", abstract: "Low-dose single-pill combinations (SPCs) are gaining recognition as an efficient therapeutic strategy for mild hypertension. However, evidence from randomized controlled trials regarding the efficacy and safety of half-dose telmisartan/amlodipine SPCs remains limited...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（safety, adverse, advers）" });
    result.push({ pmid: "42093298", title: "Laser-Assisted Management of Amlodipine-Induced Gingival Overgrowth in a Medically Complex Patient.", abstract: "BACKGROUND: Drug-induced gingival overgrowth (DIGO) is a well-recognized adverse effect associated with several systemic medications, including calcium channel blockers such as amlodipine. Management becomes particularly challenging in medically complex patients...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（bleeding, adverse, advers）" });
  }

  if (name === "氯吡格雷") {
    result.push({ pmid: "42181826", title: "Stent thrombosis associated with non-response to clopidogrel despite co-administration of aspirin and ibrutinib.", abstract: "BACKGROUND: Managing atherosclerotic cardiovascular disease in individuals with chronic lymphocytic leukaemia (CLL) is complicated by the uncertain antiplatelet effect exerted by Bruton's tyrosine kinase inhibitors...", hasAdverseEvent: "疑似", confidence: "30", reason: "摘要中少量提及ADR关键词（bleeding），需人工确认" });
    result.push({ pmid: "42177771", title: "A Patient With a Left Ventricular Assist Device Requiring Emergency Surgery for a Strangulated Umbilical Hernia: A Case Report.", abstract: "BACKGROUND Patients with left ventricular assist devices (LVADs) who require emergency non-cardiac surgery are at high risk due to long-term anticoagulation and the consequences of underlying heart failure...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（mortality, bleeding, hemorrhagic）" });
    result.push({ pmid: "42112601", title: "Generalized Bullous Fixed Drug Eruption due to Clopidogrel Hypersensitivity Successfully Treated Using the Jefferson Procedure.", abstract: "Generalized bullous fixed drug eruption (GBFDE) is a rare variant of fixed drug eruption that is known to clinically mimic Stevens-Johnson syndrome (SJS) or toxic epidermal necrolysis (TEN)...", hasAdverseEvent: "是", confidence: "85", reason: "标题直接提及ADR关键词（hypersensitivity），摘要命中2个相关词" });
  }

  if (name === "塞来昔布") {
    result.push({ pmid: "42078931", title: "Safety, tolerability, pharmacokinetics, and pharmacodynamics of zapnometinib: results from a phase I clinical study.", abstract: "INTRODUCTION: Zapnometinib (ATR-002) is a selective MEK inhibitor designed to modulate the MAPK/ERK pathway, which plays a key role in viral infections and inflammatory diseases...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 6 个ADR关键词（drug interaction, tolerability, infection, safety, adverse）" });
    result.push({ pmid: "41837970", title: "Safety and Efficacy of PrimeC in Amyotrophic Lateral Sclerosis: The PARADIGM Randomized Clinical Trial.", abstract: "IMPORTANCE: Amyotrophic lateral sclerosis (ALS) is a fatal neurodegenerative disease with limited treatment options. PrimeC is a fixed-dose oral combination of celecoxib and ciprofloxacin...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 6 个ADR关键词（death, fatal, tolerability, safety, adverse）" });
    result.push({ pmid: "41773715", title: "Therapeutic effects of Xianlinggubao capsules on knee function, inflammatory response, and bone metabolism in elderly patients with degenerative knee osteoarthritis.", abstract: "BACKGROUND: KOA is a common degenerative joint disease that often causes chronic pain, impairs daily activities, and imposes a considerable burden on patients...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（safety, adverse, advers）" });
  }

  if (name === "对乙酰氨基酚") {
    result.push({ pmid: "42146930", title: "Erector spinae plane block for opioid sparing in children undergoing laparoscopic appendectomy: a randomized controlled trial.", abstract: "BACKGROUND: Despite being a minimally invasive procedure, laparoscopic appendectomy (LA) frequently induces substantial postoperative pain in children...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（safety, adverse, advers）" });
    result.push({ pmid: "42125338", title: "Severe Acute Liver Injury Following Repeated Supratherapeutic Paracetamol Ingestion in a Child: A Case Report from a Resource-Limited Setting.", abstract: "INTRODUCTION: Paracetamol is commonly used in children and is generally considered safe when given at recommended doses...", hasAdverseEvent: "是", confidence: "85", reason: "标题直接提及ADR关键词（liver injury），摘要命中1个相关词" });
    result.push({ pmid: "42112227", title: "Clinically Suspected Acute Post-Measles Encephalitis Complicated by Paracetamol-Induced Hepatotoxicity in an Unvaccinated Child: A Case Report from a Resource-Limited Setting.", abstract: "INTRODUCTION: Measles remains a major cause of childhood morbidity and mortality in settings with low vaccination coverage...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 5 个ADR关键词（toxicity, mortality, hepatotoxicity, toxic, hepatotoxic）" });
  }

  if (name === "瑞舒伐他汀") {
    result.push({ pmid: "42133048", title: "The Effect of the combination therapy of statin and dapagliflozin...", abstract: "PURPOSE: Gliflozins (SGLT2 inhibitors) and statins are key treatments commonly used in patients with ischemic heart failure...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（mortality, adverse, advers）" });
    result.push({ pmid: "42023995", title: "Effect of Once-Daily Macitentan 75 mg on the Pharmacokinetics of Sildenafil, Riociguat, or Rosuvastatin in Healthy Male Participants.", abstract: "Macitentan is an oral, dual ETA/ETB endothelin receptor antagonist, currently approved in adults for the treatment of pulmonary arterial hypertension...", hasAdverseEvent: "疑似", confidence: "30", reason: "摘要中少量提及ADR关键词（safety），需人工确认" });
    result.push({ pmid: "41822626", title: "Reversible Thrombocytopenia Associated With Rosuvastatin Use: A Case Report.", abstract: "Statins are a class of drugs that act by inhibiting HMG-CoA reductase. As a result, their main uses include the treatment of dyslipidemia...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（side effect, adverse, advers）" });
  }

  if (name === "缬沙坦") {
    result.push({ pmid: "42194666", title: "Angioedema After Accidental Semaglutide Dosing Error: A Case Report.", abstract: "Background: Glucagon-like peptide-1 receptor agonist (GLP-1 RA) use has increased exponentially as studies show significant benefits in cardiovascular and renal diseases...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 6 个ADR关键词（side effect, angioedema, edema, hypoglycemia, oedema）" });
    result.push({ pmid: "42181918", title: "Restored Left Ventricular Mechanical Synchrony in Heart Failure with Reduced Ejection Fraction and Left Ventricular Dyssynchrony: Myocardial Work Indices Analysis.", abstract: "Left ventricle (LV) remodeling consists of structural and electrical remodeling of LV which leads to ventricular systolic dysfunction...", hasAdverseEvent: "疑似", confidence: "30", reason: "摘要中少量提及ADR关键词（hyperkalemia），需人工确认" });
    result.push({ pmid: "41931666", title: "An Unexpected Cutaneous Reaction to Valsartan in a Patient with Suspected Eczematous Pattern Toxicodermia: A Case Report.", abstract: "INTRODUCTION: Angiotensin II receptor blockers (ARBs) are a group of drugs widely used in the treatment of high blood pressure, cardiovascular and renal diseases...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（toxic, adverse, hypersensitivity, advers）" });
  }

  if (name === "达格列净") {
    result.push({ pmid: "42196606", title: "Diagnosing Metformin Intoxication with High-Resolution Platelet Respirometry: A Case Report.", abstract: "Metformin-associated lactic acidosis (MALA) involves mitochondrial Complex I inhibition, traditionally diagnosed via indirect markers...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 5 个ADR关键词（toxicity, intoxication, hypoglycemia, toxic, overdose）" });
    result.push({ pmid: "42133048", title: "The Effect of the combination therapy of statin and dapagliflozin...", abstract: "PURPOSE: Gliflozins (SGLT2 inhibitors) and statins are key treatments commonly used in patients with ischemic heart failure...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（mortality, adverse, advers）" });
    result.push({ pmid: "42021144", title: "Targeting epicardial adipose tissue in heart failure with preserved ejection fraction: exploring the dapagliflozin connection.", abstract: "BACKGROUND: Heart failure with preserved ejection fraction is the fastest-growing subtype of heart failure, especially among the elderly...", hasAdverseEvent: "否", confidence: "15", reason: "未检测到明显的不良反应关键词" });
  }

  if (name === "艾司西酞普兰") {
    result.push({ pmid: "42059569", title: "Adjuvant administration probiotic effects on sexual function in depressant men undergoing selective serotonin reuptake inhibitor treatment: a double-blinded randomized controlled trial.", abstract: "BACKGROUND: Depression is a common psychiatric disorder worldwide, often linked to complications like impaired sexual function...", hasAdverseEvent: "否", confidence: "15", reason: "未检测到明显的不良反应关键词" });
    result.push({ pmid: "42005166", title: "Inhibitor-Free Variant of the Cheung Regimen: Successful Adjunctive Therapy in Long-Standing Hypochondriasis With Prominent Somatic Features.", abstract: "Hypochondriacal obsessive-compulsive disorder (OCD) combines intrusive health anxieties with compulsive reassurance seeking and often resists high-dose selective serotonin reuptake inhibitors...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（adverse, advers）" });
    result.push({ pmid: "41909477", title: "Efficacy and Safety of Escitalopram in Alleviating Depression and Anxiety Symptoms in COPD Patients: A Randomized Double-Blind Placebo-Controlled Trial.", abstract: "PURPOSE: Depression and anxiety negatively impact COPD prognosis, yet evidence for psychopharmacological interventions remains limited...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（safety, adverse, advers）" });
  }

  if (name === "沙丁胺醇") {
    result.push({ pmid: "41762556", title: "A rare case of lung hernia associated with rib fractures and tension pneumothorax post cardiopulmonary resuscitation.", abstract: "Rib fractures are the most common injury after cardiopulmonary resuscitation (CPR) for non-traumatic cardiac arrest. Pneumothorax can evolve into tension pneumothorax...", hasAdverseEvent: "疑似", confidence: "30", reason: "摘要中少量提及ADR关键词（fatal），需人工确认" });
    result.push({ pmid: "41730555", title: "Patiromer utility as an adjunct treatment in patients needing urgent hyperkalaemia management (PLATINUM): a randomised controlled trial in the emergency department.", abstract: "OBJECTIVES: Hyperkalaemia (HK) is common in the emergency department (ED) and can cause life-threatening arrhythmias...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（advers, safety, adverse, arrhythmia）" });
    result.push({ pmid: "41666883", title: "Potassium Overdose in Patient with Chronic Kidney Disease on Losartan: A Case Report.", abstract: "INTRODUCTION: Hyperkalemic emergencies can present with weakness, paralysis, sensorimotor deficits, and potentially fatal cardiac conduction abnormalities...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 5 个ADR关键词（fatal, hyperkalemia, renal impairment, tachycardia, overdose）" });
  }

  if (name === "孟鲁司特") {
    result.push({ pmid: "41971936", title: "A successful treatment of urticaria pigmentosa with omalizumab in a pediatric patient: a case report.", abstract: "BACKGROUND: Cutaneous mastocytosis (CM) is a rare disorder characterized by abnormal mast cell proliferation limited to the skin...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（safety, adverse, advers）" });
    result.push({ pmid: "41772161", title: "Inhaled Corticosteroids Plus Tiotropium Compared to Inhaled Corticosteroids Plus Montelukast in Children with Partly Controlled/Uncontrolled Asthma: A Non-Inferiority Trial.", abstract: "OBJECTIVES: To compare the efficacy and safety of oral montelukast and inhaled tiotropium as add-on drugs to inhaled corticosteroids (ICS) in children with partly controlled/uncontrolled asthma...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（safety, adverse, neuropsychiatric, advers）" });
    result.push({ pmid: "41353847", title: "Montelukast as a novel therapeutic approach in metastatic uveal melanoma harboring a CYSLTR2 mutation: a translational case report.", abstract: "BACKGROUND: Uveal melanoma (UM), the most common primary intraocular malignancy in adults, has limited systemic treatment options in the metastatic setting...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（tolerability, adverse, advers）" });
  }

  if (name === "泮托拉唑") {
    result.push({ pmid: "42025971", title: "Biophysical and Raman Spectroscopy assessment of drug-induced photosensitivity: Insights from a randomised controlled pilot study.", abstract: "BACKGROUND: Drug-induced photosensitivity is a recognised adverse reaction, yet systematic quantification remains limited...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（adverse, advers）" });
    result.push({ pmid: "41995504", title: "Ketorolac-induced peptic ulcer bleeding after cholecystectomy in a \"healed\" ulcer patient: A CARE case report.", abstract: "RATIONALE: Ketorolac tromethamine injection-induced peptic ulcer with bleeding remains rarely reported in clinical case studies...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（infection, bleeding, safety）" });
    result.push({ pmid: "41848242", title: "[Discontinuation of long-term proton pump inhibitor treatment].", abstract: "This case report describes a 69-year-old woman on long-term pantoprazole therapy, initially prescribed for nonspecific upper gastrointestinal symptoms...", hasAdverseEvent: "否", confidence: "15", reason: "未检测到明显的不良反应关键词" });
  }

  if (name === "氯沙坦") {
    result.push({ pmid: "42175450", title: "Post COVID-19 treated with AstraZeneca vaccine exacerbates arthritis with susceptibility to herpes in an older woman: A case report.", abstract: "RATIONALE: Rheumatoid arthritis (RA) is an autoimmune inflammatory disorder that has seriously affected human health worldwide...", hasAdverseEvent: "疑似", confidence: "30", reason: "摘要中少量提及ADR关键词（infection），需人工确认" });
    result.push({ pmid: "41970069", title: "Renal Denervation in a Patient With Resistant Hypertension Using a Second-Generation Multi-electrode Catheter in Puerto Rico: A Non-pharmacological Technique for Resistant Arterial Hypertension.", abstract: "Resistant arterial hypertension poses a clinical challenge, often requiring novel interventions beyond pharmacologic therapy...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（adverse, advers）" });
    result.push({ pmid: "41931666", title: "An Unexpected Cutaneous Reaction to Valsartan in a Patient with Suspected Eczematous Pattern Toxicodermia: A Case Report.", abstract: "INTRODUCTION: Angiotensin II receptor blockers (ARBs) are a group of drugs widely used in the treatment of high blood pressure, cardiovascular and renal diseases...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（toxic, adverse, hypersensitivity, advers）" });
  }

  if (name === "美托洛尔") {
    result.push({ pmid: "42078216", title: "Profound Synergistic Bradycardia: Pharmacokinetic Consequences of Paxlovid-Mediated CYP3A4 and CYP2D6 Inhibition on Ranolazine, Diltiazem, and Metoprolol.", abstract: "Paxlovid, a codrug of nirmatrelvir/ritonavir, has established itself in the COVID-19 treatment arsenal due to numerous studies documenting clinical efficacy...", hasAdverseEvent: "否", confidence: "15", reason: "未检测到明显的不良反应关键词" });
    result.push({ pmid: "42062101", title: "Parental Advocacy in the NICU: A Unique Case of Infant Hypoglycemia Highlighting the Role of the Family in Improving Outcomes.", abstract: "Hypoglycemia, a common infant disorder caused by maternal antihypertensive medications, is a rare but serious complication...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（side effect, advers, adverse, hypoglycemia）" });
    result.push({ pmid: "41562805", title: "Statin-Associated Headache: A Rare and Underrecognized Clinical Presentation: A Case Report.", abstract: "Backgroundand Clinical Significance: Statins are widely prescribed for cardiovascular risk reduction and generally demonstrate a favorable safety profile...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（safety, adverse, advers）" });
  }

  if (name === "氟康唑") {
    result.push({ pmid: "42077724", title: "Acute Generalized Exanthematous Pustulosis Induced by Fluconazole: A Case Report.", abstract: "Acute generalized exanthematous pustulosis (AGEP) is a rare, severe type IV hypersensitivity reaction, most commonly triggered by antibiotics, calcium channel blockers, or antifungal agents...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（advers, adverse, hypersensitivity, withdrawal）" });
    result.push({ pmid: "42043354", title: "[Cutaneous Cryptococcus neoformans Infection Mimicking Necrotizing Fasciitis in a Myelofibrosis Patient Receiving Ruxolitinib: A Case Report].", abstract: "Cryptococcus neoformans is an encapsulated opportunistic yeast widely distributed in the environment and classified as critical-priority fungal pathogen by the World Health Organisation...", hasAdverseEvent: "是", confidence: "85", reason: "标题直接提及ADR关键词（infection），摘要命中2个相关词" });
    result.push({ pmid: "41914555", title: "Olorofim in combination with azole antifungals: results from the Phase 2 salvage therapy study.", abstract: "BACKGROUND: Olorofim is an antifungal agent with a novel mechanism of action against Aspergillus spp., rare moulds and dimorphic fungi...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（infection, mortality, liver injury, tolerability）" });
  }

  if (name === "阿奇霉素") {
    result.push({ pmid: "42173085", title: "Beyond the Lungs: Rising Pediatric Mycoplasma pneumoniae Infections with Extrapulmonary Manifestations in the Post-COVID-19 Pandemic Era.", abstract: "BACKGROUND: Following the relaxation of COVID-19 mitigation strategies, Mycoplasma pneumoniae (MP) infections have resurged worldwide...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（infection, adverse, advers）" });
    result.push({ pmid: "42098995", title: "Reversible Rituximab-Induced Bronchiectasis: A Pediatric Case Report and Literature Review.", abstract: "BACKGROUND Rituximab (RTX) is a chimeric IgG monoclonal antibody directed against the CD20 antigen expressed on normal and malignant B cells...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（infection, toxic）" });
    result.push({ pmid: "42054279", title: "A Rare Case of Stevens-Johnson Syndrome in a Young Patient Presenting With Odynophagia Following Antibiotic Use.", abstract: "BACKGROUND Stevens-Johnson syndrome (SJS) is a rare, immune-mediated mucocutaneous disorder usually triggered by medications or infections...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（infection, edema, withdrawal）" });
  }

  if (name === "帕罗西汀") {
    result.push({ pmid: "41987822", title: "Case Report: Fluoxetine-induced leucocytoclastic vasculitis.", abstract: "We report a case of leukocytoclastic vasculitis (LCV) in a 74-year-old woman, occurring seven months after the initiation of fluoxetine therapy for generalized anxiety disorder (GAD)...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（adverse, hypersensitivity, advers）" });
    result.push({ pmid: "41882957", title: "SSRI-Induced Galactorrhea in Adolescents.", abstract: "BACKGROUND: Selective serotonin reuptake inhibitors (SSRIs) are generally regarded as safe and widely used in children and adolescents...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（side effect, adverse, advers）" });
    result.push({ pmid: "41784061", title: "Clinical Evaluation of Drug-Drug Interactions With Aficamten.", abstract: "Aficamten is a next-in-class small molecule cardiac myosin inhibitor that was recently approved by the United States Food and Drug Administration (FDA) for the treatment of symptomatic obstructive hypertrophic cardiomyopathy (oHCM)...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（myopathy, drug interaction, adverse, advers）" });
  }

  if (name === "舍曲林") {
    result.push({ pmid: "41918580", title: "Case Report: A rare phenomenon of venlafaxine induced vocal tics.", abstract: "BACKGROUND: Venlafaxine is a serotonin norepinephrine reuptake inhibitor, an effective medication widely used in many psychiatric conditions...", hasAdverseEvent: "是", confidence: "95", reason: "摘要/标题中命中 5 个ADR关键词（side effect, neuropsychiatric, insomnia, adverse, advers）" });
    result.push({ pmid: "41882957", title: "SSRI-Induced Galactorrhea in Adolescents.", abstract: "BACKGROUND: Selective serotonin reuptake inhibitors (SSRIs) are generally regarded as safe and widely used in children and adolescents...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（side effect, adverse, advers）" });
    result.push({ pmid: "41845927", title: "Therapeutic Use of Melatonin for Gastrointestinal Motility and Hypersomnolence in a Patient With Pineal Cyst Pathology.", abstract: "BACKGROUND Pineal gland cysts are believed to alter the production and release of melatonin, which can impact the sleep/wake cycle and gastrointestinal motility...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（adverse, advers）" });
  }

  if (name === "雷米普利") {
    result.push({ pmid: "41844720", title: "Sexual function among controlled and uncontrolled hypertensive females receiving beta-blockers or ACEI/ARB and thiazides: a prospective randomized controlled study.", abstract: "BACKGROUND: Female sexual dysfunction (FSD) among females with hypertension (HTN) is frequently overlooked, with a reported prevalence of 42.1%...", hasAdverseEvent: "否", confidence: "15", reason: "未检测到明显的不良反应关键词" });
    result.push({ pmid: "41493293", title: "Using Artificial Intelligence to Adjudicate Major Adverse Cardiovascular Events in Clinical Trials.", abstract: "BACKGROUND: Major adverse cardiovascular events (MACE)-cardiovascular (CV) death, nonfatal myocardial infarction (MI), and nonfatal stroke-are highly relevant clinical outcomes...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（death, fatal, adverse, advers）" });
    result.push({ pmid: "41466925", title: "Successful Management of Angiotensin-Converting Enzyme Inhibitor-Induced Angioedema With Tranexamic Acid: A Case Report.", abstract: "Angioedema is a potentially life-threatening emergency that can present with facial swelling and airway compromise. When induced by angiotensin-converting enzyme (ACE) inhibitors (ACEIs), the mechanism is bradykinin-mediated...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（oedema, angioedema, anaphylaxis, edema）" });
  }

  if (name === "格列美脲") {
    result.push({ pmid: "41979234", title: "Efficacy and Safety of Glimepiride, Voglibose, and Metformin ER in Type 2 Diabetes: A Randomized, Active-Controlled Study.", abstract: "BACKGROUND: India ranks second in the global diabetes epidemic, with about 89 million individuals living with Type 2 diabetes mellitus (T2DM)...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（advers, safety, adverse, hypoglycemia）" });
    result.push({ pmid: "41938282", title: "A Case of Oral Semaglutide for Treatment of Hepatocyte Nuclear Factor 4A Maturity-Onset Diabetes of the Young.", abstract: "BACKGROUND/OBJECTIVE: Maturity-onset diabetes of the young (MODY) is a form of autosomal dominant monogenic diabetes. Sulfonylureas are the mainstay of therapy for hepatocyte nuclear factor 4A (HNF4A) MODY...", hasAdverseEvent: "疑似", confidence: "30", reason: "摘要中少量提及ADR关键词（hypoglycemia），需人工确认" });
    result.push({ pmid: "41925680", title: "Comparison of the Continuous Glucose Monitoring Profiles of Four Glucose-Lowering Medications in the GRADE Randomized Trial.", abstract: "OBJECTIVE: Glycemic management metrics derived from continuous glucose monitoring (CGM) are increasingly recognized as important therapeutic targets...", hasAdverseEvent: "疑似", confidence: "30", reason: "摘要中少量提及ADR关键词（hypoglycemia），需人工确认" });
  }

  if (name === "华法林") {
    result.push({ pmid: "42153925", title: "Contained Juxtarenal Aortic Perforation in the Setting of Severe Warfarin-Associated Coagulopathy.", abstract: "INTRODUCTION: Severe warfarin-associated coagulopathy is a known cause of major bleeding; however, its relationship with large-vessel structural complications remains poorly defined...", hasAdverseEvent: "是", confidence: "65", reason: "摘要命中 2 个ADR关键词（hemorrhage, bleeding）" });
    result.push({ pmid: "42093249", title: "Left Atrial Appendage Closure Complicated by Spinal Epidural Hematoma and Device-Related Thrombosis: A Case Report.", abstract: "BACKGROUND: Left atrial appendage closure (LAAC) is an important approach for stroke prevention in patients with non-valvular atrial fibrillation. Anticoagulation-related spinal epidural hematoma (SEH) and device-related thrombosis (DRT) are rare but serious complications...", hasAdverseEvent: "是", confidence: "85", reason: "摘要/标题中命中 3 个ADR关键词（bleeding, adverse, advers）" });
    result.push({ pmid: "42060815", title: "Torsemide and warfarin: A cautionary case of altered international normalized ratio and bleeding risk.", abstract: "Warfarin is a widely used oral anticoagulant with a narrow therapeutic index and multiple drug-drug interactions that may significantly alter its anticoagulant effect...", hasAdverseEvent: "是", confidence: "90", reason: "摘要/标题中命中 4 个ADR关键词（drug interaction, bleeding, adverse, advers）" });
  }

  return result;
};
